on:
 - pull_request

jobs:
    build:
        name: Build for ${{ matrix.config.plat_name }}
        strategy:
            matrix:
                config:
                 - os: ubuntu-16.04
                   plat_name: manylinux1_x86_64
                 - os: macos-10.15
                   plat_name: macosx_10_10_x86_64
                 - os: windows-2019
                   plat_name: win_amd64
        runs-on: ${{ matrix.config.os }}
        timeout-minutes: 180
        steps:
         - name: Configure git
           run: git config --global core.symlinks true

         - name: Clone repository
           uses: actions/checkout@v1

         - name: Install python 3.6
           uses: actions/setup-python@v1
           with:
               python-version: 3.6.x
               architecture: x64
         - name: Install python 2.7
           uses: actions/setup-python@v1
           with:
               python-version: 2.7.x
               architecture: x64

         - name: Build wheelhouse
           run: |
               python3 -m pip install setuptools wheel
               mkdir wheelhouse
               python3 helpers/build_package.py wheel wheelhouse
